# Generated by Django 6.0.1 on 2026-01-11 14:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField(verbose_name="留言內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="留言時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "文章留言",
                "verbose_name_plural": "文章留言列表",
                "db_table": "post_comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="按讚時間"),
                ),
            ],
            options={
                "verbose_name": "文章按讚",
                "verbose_name_plural": "文章按讚列表",
                "db_table": "post_likes",
                "ordering": ["-created_at"],
            },
        ),
    ]
