# Generated by Django 6.0.1 on 2026-01-11 19:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_initial"),
        ("posts", "0004_post_is_draft_alter_post_is_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 位址")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="瀏覽時間"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="posts.post",
                        verbose_name="瀏覽文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章瀏覽",
                "verbose_name_plural": "文章瀏覽列表",
                "db_table": "post_views",
                "ordering": ["-created_at"],
                "unique_together": {("post", "ip_address")},
            },
        ),
    ]
