# Generated by Django 6.0.1 on 2026-01-26 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0005_postcomment_ip_address_postlike_ip_address_and_more"),
        ("posts", "0006_postimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostBookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏時間"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="posts.post",
                        verbose_name="收藏文章",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="收藏者",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章收藏",
                "verbose_name_plural": "文章收藏列表",
                "db_table": "post_bookmarks",
                "ordering": ["-created_at"],
                "unique_together": {("user", "post")},
            },
        ),
    ]
