# Generated by Django 6.0.1 on 2026-01-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最後登出時間"
            ),
        ),
    ]
