# Generated by Django 6.0.1 on 2026-01-15 19:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="訂閱信箱"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否訂閱中"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="訂閱時間"),
                ),
            ],
            options={
                "verbose_name": "電子報訂閱者",
                "verbose_name_plural": "電子報訂閱列表",
                "db_table": "newsletter_subscribers",
                "ordering": ["-created_at"],
            },
        ),
    ]
