# Generated by Django 6.0.1 on 2026-01-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="訂閱者暱稱"
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="unsubscribed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="取消訂閱時間"
            ),
        ),
    ]
