# Generated by Django 6.0.1 on 2026-01-11 14:05

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="分類 UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="分類名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="分類描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "文章分類",
                "verbose_name_plural": "文章分類列表",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="文章 UUID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文章標題")),
                (
                    "slug",
                    models.SlugField(
                        max_length=200, unique=True, verbose_name="文章別名"
                    ),
                ),
                ("content", models.TextField(verbose_name="文章內容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="發布時間"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="是否封存"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否發布"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章列表",
                "db_table": "posts",
                "ordering": ["-published_at", "-updated_at", "-created_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="標籤 UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="標籤名稱"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="標籤描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "文章標籤",
                "verbose_name_plural": "文章標籤列表",
                "db_table": "tags",
            },
        ),
    ]
