# Generated by Django 6.0.1 on 2026-01-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover_image",
            field=models.ImageField(
                blank=True, help_text="文章縮圖", null=True, upload_to="covers/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(blank=True, null=True, verbose_name="文章摘要"),
        ),
    ]
