# Generated by Django 6.0.1 on 2026-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_cover_image_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(default=True, verbose_name="是否為草稿"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="是否發布"),
        ),
    ]
