# Generated by Django 6.0.1 on 2026-01-15 16:43

import uuid

import django.db.models.deletion
from django.db import migrations, models

import utils.image_handler


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_remove_post_categories_post_category_alter_post_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="圖片 UUID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=utils.image_handler.post_image_upload_path,
                        verbose_name="圖片檔案",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="替代文字"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上傳時間"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="posts.post",
                        verbose_name="所屬文章",
                    ),
                ),
            ],
            options={
                "verbose_name": "文章圖片",
                "verbose_name_plural": "文章圖片列表",
                "db_table": "post_images",
            },
        ),
    ]
